spring:
  security:
    jwt:
      secret: it-is-a-super-secret-for-jwt
      expiration: 86400000 # one day in ms
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migrations/users
    default-schema: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: password
    hikari:
      schema: users