openapi: 3.0.0
info:
  title: User Management
  version: 1.0.0
  description: User Management endpoints
paths:
  /v1/users:
    post:
      summary: Create a user
      operationId: create
      tags:
        - user
      requestBody:
        description: Creation User Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreationUserRequest'
      responses:
        '201':
          description: Created

components:
  schemas:
    CreationUserRequest:
      type: object
      required:
        - id
        - username
        - password
        - email
        - last_name
        - first_name
      properties:
        id:
          type: string
          format: uuid
          example: '66a822be-b28a-4258-9a51-f6bd017ba0fe'
        username:
          type: string
          maxLength: 15
          minLength: 5
          example: 'jdoe'
        email:
          type: string
          format: email
          example: 'jdoe@example.com'
        password:
          type: string
          minLength: 5
          maxLength: 25
        first_name:
          type: string
          minLength: 1
          maxLength: 50
          example: 'John'
        last_name:
          type: string
          minLength: 1
          maxLength: 50
          example: 'Doe'
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: 'Invalid field_name'
