apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-users
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /v1/auth
            pathType: Prefix
            backend:
              service:
                name: ms-users
                port:
                  number: 8080
          - path: /v1/roles
            pathType: Prefix
            backend:
              service:
                name: ms-users
                port:
                  number: 8080